# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: whaler
  username: whaler
  password: admin
  host: localhost
  port: 3306

test:
  <<: *default
  database: DBNAME
  username: usr
  password: paswd
  shost: localhost

production:
  database: DBNAME
  <<: *default
  username: usr
  password: paswd
  shost: localhost
