# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a82ce399e606cd97c224a7c8db9d91a8dae27556c70bccd768875592c5f986896d1b53c2a0c5f5079f5be7572a0faf89363a1f755276307c54d407277c49be7

test:
  secret_key_base: ad87f73ccc335e96c5f25a4cae06728a0088486a8c004875d638d389ebee72a840a7e93346b7ced8c10a845bc381b7d1352149fb00286cd149a968284da7c639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
